import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const docsDir = path.resolve(process.cwd(), 'docs');
const sidebarPath = path.join(docsDir, '_sidebar.md');
const docsifyReservedFiles = new Set(['_sidebar.md', '_navbar.md']);
const homeLabel = '\u9996\u9875';

function toDocsPath(filePath) {
  return path.relative(docsDir, filePath).split(path.sep).join('/');
}

function isArchivedEntry(name) {
  return name.startsWith('_') && !docsifyReservedFiles.has(name);
}

function prettifySegment(segment) {
  return segment
    .replace(/[-_]+/g, ' ')
    .replace(/\b\w/g, (letter) => letter.toUpperCase());
}

function getTitle(filePath) {
  const content = readFileSync(filePath, 'utf8');
  const heading = content.match(/^\s*#\s+(.+?)\s*#*\s*$/m);

  if (heading) {
    return heading[1]
      .replace(/[`*_~]/g, '')
      .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
      .trim();
  }

  return prettifySegment(path.basename(filePath, '.md'));
}

function collectMarkdownFiles(dir) {
  const entries = readdirSync(dir, { withFileTypes: true })
    .filter((entry) => !entry.name.startsWith('.') && !isArchivedEntry(entry.name))
    .sort((a, b) => {
      if (a.isDirectory() !== b.isDirectory()) {
        return a.isDirectory() ? -1 : 1;
      }

      return a.name.localeCompare(b.name, 'zh-CN');
    });

  const files = [];

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);

    if (entry.isDirectory()) {
      files.push(...collectMarkdownFiles(fullPath));
      continue;
    }

    if (
      entry.isFile() &&
      entry.name.endsWith('.md') &&
      !docsifyReservedFiles.has(entry.name)
    ) {
      files.push(fullPath);
    }
  }

  return files;
}

function buildSidebar() {
  const files = collectMarkdownFiles(docsDir);
  const rootReadme = path.join(docsDir, 'README.md');
  const lines = ['<!-- Auto-generated by scripts/generate-sidebar.mjs -->'];
  const groupedFiles = new Map();

  if (files.includes(rootReadme)) {
    lines.push('', `* [${homeLabel}](/)`);
  }

  for (const file of files) {
    if (file === rootReadme) {
      continue;
    }

    const relativePath = toDocsPath(file);
    const [groupName] = relativePath.split('/');

    if (!groupedFiles.has(groupName)) {
      groupedFiles.set(groupName, []);
    }

    groupedFiles.get(groupName).push({
      title: getTitle(file),
      href: relativePath
    });
  }

  for (const [groupName, groupFiles] of groupedFiles) {
    lines.push('', `* ${prettifySegment(groupName)}`);

    for (const file of groupFiles) {
      lines.push(`  * [${file.title}](${file.href})`);
    }
  }

  lines.push('');
  return lines.join('\n');
}

writeFileSync(sidebarPath, buildSidebar(), 'utf8');
console.log(`Generated ${toDocsPath(sidebarPath)}`);
